# Generated by Django 4.0.6 on 2022-07-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('last_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AcaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date_price', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.acao')),
            ],
        ),
    ]
