# Generated by Django 4.0.6 on 2022-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_alter_acaohistorico_date_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
