# Generated by Django 4.0.6 on 2022-07-18 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alpha', '0004_alter_acaohistorico_date_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID unico para identificar uma ação em especial', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AcaoDono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateTimeField(default=django.utils.timezone.now)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.acao')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
