# Generated by Django 4.0.6 on 2022-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_alter_acao_id_alter_acaohistorico_date_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaodono',
            name='date_buy',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
