# Generated by Django 4.0.6 on 2022-07-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0007_alter_acao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaodono',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
