# Generated by Django 4.0.6 on 2022-07-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0009_alter_acaohistorico_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaodono',
            name='date_buy',
        ),
    ]
