# Generated by Django 4.0.6 on 2022-07-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0010_remove_acaodono_date_buy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaohistorico',
            options={},
        ),
        migrations.RemoveField(
            model_name='acaohistorico',
            name='date_price',
        ),
    ]
