# Generated by Django 4.0.6 on 2022-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0011_alter_acaohistorico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaohistorico',
            options={'ordering': ['-date_price']},
        ),
        migrations.AddField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(default='date published'),
        ),
    ]
