# Generated by Django 4.0.6 on 2022-07-25 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0012_remove_acaodono_buy_price_acaodono_acaodatacompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaodono',
            name='acaodatacompra',
        ),
        migrations.AddField(
            model_name='acaodono',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='acaodono',
            name='date_buy',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
