# Generated by Django 4.0.6 on 2022-07-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0013_alter_acaohistorico_date_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaodono',
            name='date_buy',
            field=models.TimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.TimeField(default='timezone.now'),
        ),
    ]
