# Generated by Django 4.0.6 on 2022-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0013_remove_acaodono_acaodatacompra_acaodono_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaodono',
            name='date_buy',
        ),
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
