# Generated by Django 4.0.6 on 2022-07-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0014_remove_acaodono_date_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(),
        ),
    ]
