# Generated by Django 4.0.6 on 2022-07-25 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alpha', '0015_alter_acaohistorico_date_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date_buy', models.DateTimeField()),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.acao')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AcaoDono',
        ),
    ]
