# Generated by Django 4.0.6 on 2022-07-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0015_remove_acaodono_date_buy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
