# Generated by Django 4.0.6 on 2022-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0017_delete_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaohistorico',
            name='date_price',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
