# Generated by Django 4.0.6 on 2022-07-25 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0018_alter_acaohistorico_date_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaodono',
            name='date_buy',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
