# Generated by Django 4.0.6 on 2022-07-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0019_acaodono_date_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaodono',
            name='date_buy',
        ),
    ]
